In [2]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

## Tensors

In [10]:
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)
print(V[0])
print(V[0].item())

tensor([1., 2., 3.])
tensor(1.)
1.0


In [15]:
# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)
print(M[0])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1., 2., 3.])


In [16]:
# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)
print(T[0])

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[1., 2.],
        [3., 4.]])


#### Create a tensor of random floats.

In [18]:
torch.rand((3, 4, 5))

tensor([[[0.1768, 0.8248, 0.8036, 0.9434, 0.2197],
         [0.4177, 0.4903, 0.5730, 0.1205, 0.1452],
         [0.7720, 0.3828, 0.7442, 0.5285, 0.6642],
         [0.6099, 0.6818, 0.7479, 0.0369, 0.7517]],

        [[0.1484, 0.1227, 0.5304, 0.4148, 0.7937],
         [0.2104, 0.0555, 0.8639, 0.4259, 0.7812],
         [0.6607, 0.1251, 0.6004, 0.6201, 0.1652],
         [0.2628, 0.6705, 0.5896, 0.2873, 0.3486]],

        [[0.9579, 0.4075, 0.7819, 0.7165, 0.1768],
         [0.0748, 0.9799, 0.5261, 0.8427, 0.6036],
         [0.6608, 0.8735, 0.9741, 0.1682, 0.5625],
         [0.8731, 0.8622, 0.8106, 0.1381, 0.1399]]])

In [19]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
print(x + y)

tensor([5., 7., 9.])
